-- Star Field art. The first palette is the text palette: text(..., "w"), ui colours, rect colours.
palette main
  . clear
  k #1a1c2c ink
  w #f4f4f4 white
  s #ffcd75 skin
  o #8f563b hair
  b #3b5dc9 blue
  y #ffe45c yellow
  r #b13e53 red
  g #38b764 grass
  d #257179 grassdark
  l #a7f070 lime
  m #566c86 stone
  n #94b0c2 stonelight

-- ---------- hero (faces right; the kit flips it for left) ----------
sprite hero1 16x16 pal=main
................
.....kkkkkk.....
....koooooook...
....koosssksk...
....kosssssk....
.....kssssk.....
....kbbbbbbk....
...kbbbbbbbbk...
...ksbbbbbbsk...
...kkbbbbbbkk...
....kbbbbbbk....
....kbbkkbbk....
....kook.kook...
....kkk..kkk....
................
................
sprite hero2 16x16 pal=main
................
.....kkkkkk.....
....koooooook...
....koosssksk...
....kosssssk....
.....kssssk.....
....kbbbbbbk....
...kbbbbbbbbk...
...ksbbbbbbsk...
...kkbbbbbbkk...
....kbbbbbbk....
....kbbkkbbk....
...kook..kook...
...kkk....kkk...
................
................
clip hero_walk fps=8 hero1 hero2

-- ---------- slime ----------
sprite slime1 16x16 pal=main
................
................
................
................
................
................
......kkkk......
....kkllllkk....
...kllllllwlk...
..klkklllkkwlk..
..klkklllkklllk.
..klllllllllllk.
..kgllllllllgk..
...kgggggggggk..
....kkkkkkkkk...
................
sprite slime2 16x16 pal=main
................
................
................
................
................
................
................
................
.....kkkkkk.....
...kkllllllkk...
..klkklllkkwlk..
.klllllllllllk..
.kgllllllllllgk.
..kgggggggggk...
...kkkkkkkkkk...
................
clip slime_hop fps=4 slime1 slime2

-- ---------- pickups + HUD ----------
sprite star 16x16 pal=main
................
.......kk.......
......kyyk......
......kyyk......
..kkkkyyyykkkk..
..kyyyyyyyyyyk..
...kyyyyyyyyk...
....kyyyyyyk....
....kyyyyyyk....
...kyyykkyyyk...
...kyyk..kyyk...
..kyyk....kyyk..
..kkk......kkk..
................
................
................
sprite heart 8x8 pal=main
.kk.kk..
krrkrrk.
krrrrrk.
krrrrrk.
.krrrk..
..krk...
...k....
........
sprite heart0 8x8 pal=main
.kk.kk..
kmmkmmk.
kmmmmmk.
kmmmmmk.
.kmmmk..
..kmk...
...k....
........

-- ---------- tiles ----------
tile grass 16x16 pal=main
gggggggggggggggg
gggggggggggggggg
ggdgggggggggggdg
gggggggggggggggg
gggggggggdgggggg
gggggggggggggggg
gggggggggggggggg
ggggdggggggggggg
gggggggggggggggg
gggggggggggggdgg
gggggggggggggggg
gggggggggggggggg
gdgggggggdgggggg
gggggggggggggggg
gggggggggggggggg
gggggggggggggggg
tile rock 16x16 pal=main flags=solid
kkkkkkkkkkkkkkkk
knnnnnnnnnnnnnmk
knnnnnnnnnnnnmmk
knnmmmmmmmmmmmmk
knnmmmmmmmmmmmmk
knmmmmmmmmmmmmmk
knmmmmmmmmmmmmmk
knmmmmmmmmmmmmmk
kkkkkkkkkkkkkkkk
knnnnnnkknnnnnmk
knnmmmmkknnmmmmk
knmmmmmkknmmmmmk
knmmmmmkknmmmmmk
knmmmmmkknmmmmmk
knmmmmmkknmmmmmk
kkkkkkkkkkkkkkkk

-- ---------- the room: 20x15 tiles; row 0 sits under the HUD ----------
map field 20x15
legend # rock  , grass
legend P @hero:grass  * @star:grass  S @slime:grass
####################
#,,,,,,,,,,,,,,,,,,#
#,,,,,,,,,,,,,,,,*,#
#,,,,,,,,,,,,,,,,,,#
#,,,,,##,,,,,,,,,,,#
#,,,,,##,,,,,,,S,,,#
#,,,,,,,,,,,,,,,,,,#
#,,P,,,,,,,*,,,,,,,#
#,,,,,,,,,,,,,,,,,,#
#,,,,,,,,,,,,##,,,,#
#,,,,,,,,,,,,##,,,,#
#,,,,,,,,,,,,,,,,,,#
#,,*,,,,,,,,,,,,,,,#
#,,,,,,,,,,,,,,,,,,#
####################
