-- Froggy assets (generated by gen.py from hand-drawn grids)

palette ui
  . clear
  w #ffffff white
  y #ffd23f yellow
  r #ff5a5a red
  g #7cff6b green
  k #0b0b14 ink
  c #6fe3ff cyan
  o #ffa23c orange
  n #16213a panel
  N #2c3f6b panelEdge
  p #ff8fc8 pink

palette pfrog
  . clear
  k #0f2e14 outline
  g #58d63f green
  G #2f9a2a dark
  y #c9f76b belly
  w #ffffff eye
  e #101010 pupil
  r #d9372b red

palette carY
  . clear
  k #111118 ink
  d #4a4a58 tyre
  b #e8c02a body
  s #fff4a8 shine
  h #fff7c2 light
  w #9fd8ff glass

palette carR
  . clear
  k #111118
  d #4a4a58
  b #e2463a
  s #ff9b8f
  h #fff7c2
  w #9fd8ff

palette carP
  . clear
  k #111118
  d #4a4a58
  b #d962c8
  s #f6a8ec
  h #fff7c2
  w #9fd8ff

palette carG
  . clear
  k #111118
  d #4a4a58
  b #3ec9c0
  s #a8f3ee
  h #fff7c2
  w #9fd8ff

palette ptruck
  . clear
  k #111118
  d #4a4a58
  b #f0f0f0
  s #ffffff
  h #fff7c2
  w #9fd8ff
  t #c9c9d6 trailer
  T #9a9aab trailerDark

palette plog
  . clear
  k #2b1508 ink
  b #7a4a21 bark
  B #99602c barkLight
  l #d9a260 ring
  r #52300f barkDark

palette pturtle
  . clear
  k #0e2616 ink
  s #d0402f shell
  S #8e2a1f shellDark
  g #72d06a skin
  G #3f9a4a skinDark
  y #ffcf5a rim
  w #ffffff eye

palette plily
  . clear
  k #0d4a1e ink
  g #43c052 pad
  G #2a8f3a padDark
  p #ff8fc8 petal
  y #ffe066 heart

palette pwater
  . clear
  d #1a3a8c deep
  b #2350b0 blue
  l #4c84e6 light
  w #a8ccff foam

palette pland
  . clear
  p #6b4f9e purple
  P #54397f purpleDark
  q #8c71c4 purpleLight
  a #2a2a33 asphalt
  A #34343f asphaltLight
  W #e6e6e6 paint
  Y #f2c230 yellowPaint
  h #1f5e2a hedge
  H #2e8038 hedgeLight
  j #56b04a leaf
  x #103a17 hedgeDark
  K #0b0b14 hud

palette plogo
  . clear
  k #0b2a10 ink
  g #7cff6b fill
  G #3fbf3a fillDark
  w #eaffd0 shine

sprite frog_u 16x16 pal=pfrog
................
.kk..........kk.
kGgk.kkkkkk.kgGk
.kgkkwekkewkkgk.
..kgkwwkkwwkgk..
...kgkkggkkgk...
...kggGGGGggk...
..kgGyyyyyyGgk..
.kgGyyyyyyyyGgk.
.kgGyyyyyyyyGgk.
..kgGyyyyyyGgk..
..kkgGGggGGgkk..
.kgkkggggggkkgk.
kGgk.kkkkkk.kgGk
.kk..........kk.
................

sprite frog_uh 16x16 pal=pfrog
.kk..........kk.
kGgk........kgGk
.kgk.kkkkkk.kgk.
..kgkwekkewkgk..
...kkwwkkwwkk...
...kgkkggkkgk...
...kggGGGGggk...
..kgGyyyyyyGgk..
..kgGyyyyyyGgk..
...kgGyyyyGgk...
...kkGGggGGkk...
....kkggggkk....
...kgkkkkkkgk...
..kgk......kgk..
.kGgk......kgGk.
..kk........kk..

sprite frog_s 16x16 pal=pfrog
..k..........k..
.kGk....kk..kGk.
.kggk..kggkkggk.
..kkgkkgGGgkkk..
...kkggGyyGgk...
..kwwkgyyyyGgk..
..kewkGyyyyGgk..
..kkkgGyyyyggk..
..kkkgGyyyyggk..
..kewkGyyyyGgk..
..kwwkgyyyyGgk..
...kkggGyyGgk...
..kkgkkgGGgkkk..
.kggk..kggkkggk.
.kGk....kk..kGk.
..k..........k..

sprite frog_sh 16x16 pal=pfrog
.k..............
kGk...........k.
kggk...kk....kGk
.kkgkkkggkk.kggk
...kkggGGgkkgkk.
..kwwkgyyGGkk...
..kewkGyyyGgk...
..kkkgGyyyggk...
..kkkgGyyyggk...
..kewkGyyyGgk...
..kwwkgyyGGkk...
...kkggGGgkkgkk.
.kkgkkkggkk.kggk
kggk...kk....kGk
kGk...........k.
.k..............

sprite splat 16x16 pal=pfrog
................
..r.......r.....
...r..rr.....r..
.....rrrr..rr...
..rr.rgGgrrr....
.....gGggGgr..r.
...rgGgyygGgr...
r..rgGyyyyGgrr..
...rrgyyyygGr...
....rgGyygGg....
..r..rgGgGr.r...
....rr.rrr..r...
..r..r....r.....
......r...rr....
...r......r.....
................

sprite skull 16x16 pal=pfrog
................
................
....kkkkkkkk....
...kwwwwwwwwk...
..kwwwwwwwwwwk..
..kwwwwwwwwwwk..
..kwkkkwwkkkwk..
..kwkkkwwkkkwk..
..kwwwwkkwwwwk..
...kwwwwwwwwk...
....kwkwkwkk....
....kwwwwwwk....
.....kkkkkk.....
................
................
................

sprite splash1 16x16 pal=pwater
................
................
................
................
................
......w..w......
.....w.ww.w.....
....w.wllw.w....
....w.wllw.w....
.....w.ww.w.....
......w..w......
................
................
................
................
................

sprite splash2 16x16 pal=pwater
................
................
...w........w...
....w..ww..w....
..w..w....w..w..
...w........w...
..w..........w..
.w.....ll.....w.
.w.....ll.....w.
..w..........w..
...w........w...
..w..w....w..w..
....w..ww..w....
...w........w...
................
................

sprite splash3 16x16 pal=pwater
................
.w............w.
................
...w..w..w..w...
................
w..............w
................
w......ww......w
................
w..............w
................
...w..w..w..w...
................
.w............w.
................
................

clip splash fps=10 splash1 splash2 splash3 splash3

sprite car 16x16 pal=carY
................
..kkk.....kkk...
..kdk.....kdk...
.kkkkkkkkkkkkkk.
kbbsbbbbbbbbbbbk
khbwwkbbsbbwkbbk
khbwwkbbbbbwkbbk
kbbwwkbbbbbwkbbk
kbbwwkbbbbbwkbbk
khbwwkbbbbbwkbbk
khbwwkbbsbbwkbbk
kbbsbbbbbbbbbbbk
.kkkkkkkkkkkkkk.
..kdk.....kdk...
..kkk.....kkk...
................

sprite racer 16x16 pal=carY
................
.kkk.......kkk..
.kdk.......kdk..
..k.........k...
...kkkkkkkkk.kk.
kkkbbbbbbbbbkbbk
hbbbbwwkbbbbbbbk
bsbbbwwkbsssbbbk
bsbbbwwkbsssbbbk
hbbbbwwkbbbbbbbk
kkkbbbbbbbbbkbbk
...kkkkkkkkk.kk.
..k.........k...
.kdk.......kdk..
.kkk.......kkk..
................

sprite truck 32x16 pal=ptruck
................................
..kkk..kkk..........kkk...kkk...
..kdk..kdk..........kdk...kdk...
.kkkkkkkkk.kkkkkkkkkkkkkkkkkkkk.
kbbbbbbbbkkkttttttttttttttttttTk
khbwwkbbbkktttttttttttttttttttTk
khbwwkbsbkktTTTTTTTTTTTTTTTTTtTk
kbbwwkbsbkktttttttttttttttttttTk
kbbwwkbsbkktttttttttttttttttttTk
khbwwkbsbkktTTTTTTTTTTTTTTTTTtTk
khbwwkbbbkktttttttttttttttttttTk
kbbbbbbbbkkkttttttttttttttttttTk
.kkkkkkkkk.kkkkkkkkkkkkkkkkkkkk.
..kdk..kdk..........kdk...kdk...
..kkk..kkk..........kkk...kkk...
................................

sprite log_l 16x16 pal=plog
................
................
...kkkkkkkkkkkkk
..kllkBBBBBlBBBB
.klBBlkbbbbbbrbb
.klBkBlkBBlBBBBB
klBkrkBlkbbbrbbb
klBkrkBlkbbbbbbb
klBkrkBlkBBBBBBB
klBkkBlkbbbrbbbb
.klBBlkbbbbbbbrb
.kllBlkbrrrbbbbb
..kllkrrrrrrrrrr
...kkkkkkkkkkkkk
................
................

sprite log_m 16x16 pal=plog
................
................
kkkkkkkkkkkkkkkk
BBBlBBBBBBBlBBBB
bbbbbrbbbbbbbrbb
BBBBBBBBlBBBBBBB
bbrbbbbbbbbrbbbb
bbbbbbbbbbbbbbbb
BBBBBlBBBBBBBBBB
bbbbbbbbbrbbbbbb
bbrbbbbbbbbbbbrb
rrrrbbbbrrrrbbbb
rrrrrrrrrrrrrrrr
kkkkkkkkkkkkkkkk
................
................

sprite log_r 16x16 pal=plog
................
................
kkkkkkkkkkkkk...
BBBlBBBBBBBBkk..
bbbbbrbbbbBBBBk.
BBBBBBBlBBBBBBk.
bbrbbbbbbbbbBBBk
bbbbbbbbbbbbBBBk
BBBBBlBBBBBBBBBk
bbbbbbbbbrbbbBk.
bbrbbbbbbbbbbrk.
rrrrbbbbrrrrrk..
rrrrrrrrrrrrk...
kkkkkkkkkkkk....
................
................

sprite turtle1 16x16 pal=pturtle
................
...kk......kk...
..kgGk....kgGk..
...kkkkkkkkkk...
..kySsssSSssyk..
.kkSsSSssSSsSyk.
kgkSsSssssSsSSk.
kggSSssyyssSSSk.
kwgSSssyyssSSSk.
kgkSsSssssSsSSk.
.kkSsSSssSSsSyk.
..kySsssSSssyk..
...kkkkkkkkkk...
..kgGk....kgGk..
...kk......kk...
................

sprite turtle2 16x16 pal=pturtle
................
................
.kgGk......kgGk.
..kkkkkkkkkkkk..
..kySsssSSssyk..
.kkSsSSssSSsSyk.
kgkSsSssssSsSSk.
kggSSssyyssSSSk.
kwgSSssyyssSSSk.
kgkSsSssssSsSSk.
.kkSsSSssSSsSyk.
..kySsssSSssyk..
..kkkkkkkkkkkk..
.kgGk......kgGk.
................
................

clip turtle fps=4 turtle1 turtle2

sprite lily 16x16 pal=plily
................
....kkkkkkk.....
..kkgggggkgkk...
.kgggGggk.kggk..
.kggggggk.kgggk.
kgggGgggggggGgk.
kggggggppgggggk.
kgGgggppyppggGgk
kggggggppgggggk.
kgggggGgggggGgk.
.kggGggggggggk..
.kkggggGggggkk..
...kkggggggkk...
.....kkkkkk.....
................
................

sprite panel 32x16 pal=ui
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn

sprite lifefrog 8x8 pal=pfrog
kk....kk
kgkwwkgk
.kgwegk.
.kgyygk.
kgyyyygk
.kgyygk.
kgkggkgk
kk....kk

sprite tbar 8x8 pal=ui
........
.gggggg.
.gggggg.
.gggggg.
.gggggg.
.gggggg.
.gggggg.
........

sprite tbarlow 8x8 pal=ui
........
.rrrrrr.
.rrrrrr.
.rrrrrr.
.rrrrrr.
.rrrrrr.
.rrrrrr.
........

sprite LF 16x16 pal=plogo
..kkkkkkkkkkkk..
..kwwwwwwwwwwk..
..kGGGGGGGGGGk..
..kggkkkkkkkkk..
..kGGk..........
..kggk..........
..kGGkkkkkkk....
..kggggggggk....
..kGGGGGGGGk....
..kggkkkkkkk....
..kGGk..........
..kggk..........
..kGGk..........
..kggk..........
..kGGk..........
..kkkk..........

sprite LR 16x16 pal=plogo
..kkkkkkkkkk....
..kwwwwwwwwk....
..kGGGGGGGGkkk..
..kggkkkkkkggk..
..kGGk....kGGk..
..kggk....kggk..
..kGGkkkkkkGGk..
..kggggggggkkk..
..kGGGGGGGGk....
..kggkkggkkk....
..kGGkkGGkkk....
..kggkkkkggk....
..kGGk..kGGkkk..
..kggk..kkkggk..
..kGGk....kGGk..
..kkkk....kkkk..

sprite LO 16x16 pal=plogo
....kkkkkkkk....
....kwwwwwwk....
..kkkGGGGGGkkk..
..kggkkkkkkggk..
..kGGk....kGGk..
..kggk....kggk..
..kGGk....kGGk..
..kggk....kggk..
..kGGk....kGGk..
..kggk....kggk..
..kGGk....kGGk..
..kggk....kggk..
..kGGkkkkkkGGk..
..kkkggggggkkk..
....kGGGGGGk....
....kkkkkkkk....

sprite LG 16x16 pal=plogo
....kkkkkkkk....
....kwwwwwwk....
..kkkGGGGGGkkk..
..kggkkkkkkggk..
..kGGk....kGGk..
..kggk....kkkk..
..kGGkkkkkkkkk..
..kggkkggggggk..
..kGGkkGGGGGGk..
..kggkkkkkkggk..
..kGGk....kGGk..
..kggk....kggk..
..kGGkkkkkkGGk..
..kkkggggggggk..
....kGGGGGGGGk..
....kkkkkkkkkk..

sprite LY 16x16 pal=plogo
..kkkk....kkkk..
..kwwk....kwwk..
..kGGk....kGGk..
..kggk....kggk..
..kGGkkkkkkGGk..
..kkkggkkggkkk..
....kGGkkGGk....
....kkkggkkk....
......kGGk......
......kggk......
......kGGk......
......kggk......
......kGGk......
......kggk......
......kGGk......
......kkkk......

tile water 16x16 pal=pwater
bbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbb
bbbllbbbbbbbbbbb
bbbbbllllbbbbbbb
bbbbbbbbbbbbbbbb
bbbbbbbbbbbbdbbb
bdbbbbbbbbbllbbb
bbbbbbbbbbbbbllb
bbbbbbbbbbbbbbbb
bbbbbbdbbbbbbbbb
blbbbbbbbbbbbbbb
bbllbbbbbbbbbbbb
bbbbbbbbblllbbbb
bbbbbbbbbbbbwlbb
bbbbdbbbbbbbbbbb
bbbbbbbbbbbbbbbb

tile side 16x16 pal=pland
PPPPPPPPPPPPPPPP
pqpppppppqpppppp
pqpppppppqpppppp
pqpppppppqpppppp
pPPPPPPPPpPPPPPP
qqqqqqpqqqqqqqqp
ppppppqpppppppqp
ppppppqpppppppqp
pppppppPpppppppq
PPPPPPPPPPPPPPPP
pqpppppppqpppppp
pqpppppppqpppppp
pqpppppppqpppppp
pPPPPPPPPpPPPPPP
qqqqqqpqqqqqqqqp
ppppppqpppppppqp

tile road 16x16 pal=pland
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaAaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaAaaaaaaaaaAaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaAaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa

tile roaddash 16x16 pal=pland
aaWWWWWWWWaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaAaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaAaaaaaaaaaAaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaAaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa

tile roadedge 16x16 pal=pland
YYYYYYYYYYYYYYYY
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaAaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaAaaaaaaaaaAaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaAaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa

tile hedge 16x16 pal=pland
xxhxxxxhxxxxxhxx
xhHhxxhHhxxxhHhx
hHjHhhHjHhxhHjHh
HjjHhHjjHhhHjjHh
hHHhhhHHhhHhHHhh
hhhHhhhhhHjHhhhH
hhHjHhhhHjjHhhHj
hHjjHhhhhHHhhHjj
hhHHhhHhhhhhhhHH
hhhhhHjHhhhHhhhh
hhHhhHjjHhHjHhhh
hHjHhhHHhhHjjHhh
hhHhhhhhhhhHHhhh
xhhhhxhhhhxhhhhx
xxhhxxxhhxxxhhxx
xxxxxxxxxxxxxxxx

tile hud 16x16 pal=pland
KKKKKKKKKKKKKKKK
KKKKKKKKKKKKKKKK
KKKKKKKKKKKKKKKK
KKKKKKKKKKKKKKKK
KKKKKKKKKKKKKKKK
KKKKKKKKKKKKKKKK
KKKKKKKKKKKKKKKK
KKKKKKKKKKKKKKKK
KKKKKKKKKKKKKKKK
KKKKKKKKKKKKKKKK
KKKKKKKKKKKKKKKK
KKKKKKKKKKKKKKKK
KKKKKKKKKKKKKKKK
KKKKKKKKKKKKKKKK
KKKKKKKKKKKKKKKK
KKKKKKKKKKKKKKKK

map sea 20x15
legend ~ water
~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~

map level 20x15
legend H hedge  s side  r road  d roaddash  e roadedge  K hud
KKKKKKKKKKKKKKKKKKKK
H..HH..HH..HH..HH..H
....................
....................
....................
....................
....................
ssssssssssssssssssss
eeeeeeeeeeeeeeeeeeee
dddddddddddddddddddd
dddddddddddddddddddd
dddddddddddddddddddd
dddddddddddddddddddd
ssssssssssssssssssss
KKKKKKKKKKKKKKKKKKKK
