-- Pirate Treasure art. The first palette is the text palette: text(..., "w"), ui colours, rect colours.
palette main
  . clear
  k #1a1c2c ink
  w #f4f4f4 white
  s #ffcd75 skin
  r #b13e53 red
  n #29366f navy
  o #8f563b brown
  y #ffe45c gold
  c #ef7d57 orange
  d #ab3428 crabdark
  a #f6d7a1 sand
  t #d1a05c sandshade
  u #3b5dc9 water
  v #41a6f6 foam
  m #566c86 stone
  l #94b0c2 stonelight

-- ---------- pirate hero (faces right; the kit flips it for left) ----------
sprite pirate1 16x16 pal=main
................
.....rrrrrr.....
....krrrrrrrk...
....krrsssksk...
....krsssssk....
.....kssssk.....
....knnnnnnk....
...knnnnnnnnk...
...ksnnnnnnsk...
...kknnnnnnkk...
....knnnnnnk....
....knnkknnk....
....kook.kook...
....kkk..kkk....
................
................
sprite pirate2 16x16 pal=main
................
.....rrrrrr.....
....krrrrrrrk...
....krrsssksk...
....krsssssk....
.....kssssk.....
....knnnnnnk....
...knnnnnnnnk...
...ksnnnnnnsk...
...kknnnnnnkk...
....knnnnnnk....
....knnkknnk....
...kook..kook...
...kkk....kkk...
................
................
clip pirate_walk fps=8 pirate1 pirate2

-- ---------- crab (scuttles side to side) ----------
sprite crab1 16x16 pal=main
................
................
................
................
................
....k......k....
...kwk....kwk...
..dccccccccccd..
ccdccccccccccdcc
.kdccccccccccdk.
.kdccccccccccdk.
..dccccccccccd..
...k..k..k..k...
................
................
................
sprite crab2 16x16 pal=main
................
................
................
................
................
....k......k....
...kwk....kwk...
..dccccccccccd..
ccdccccccccccdcc
.kdccccccccccdk.
.kdccccccccccdk.
..dccccccccccd..
....k..k..k..k..
................
................
................
clip crab_walk fps=6 crab1 crab2

-- ---------- parrot ----------
sprite parrot 16x16 pal=main
................
................
................
.....kkk........
....kyykk.......
....kyykk.......
....kyykk.......
....kyykk.......
.....kkk........
........kkk.....
.........cck....
.........cck....
........cck.....
.........kk.....
................
................

-- ---------- treasure chest + HUD hearts ----------
sprite chest 16x16 pal=main
................
................
................
..kkkkkkkkkkkk..
..kooooooooook..
..kooooooooook..
..kkkkkkkkkkkk..
..kooooooooook..
..kooooooooook..
..kooooooooook..
..kooooooooook..
..kkkkkkkkkkkk..
................
................
................
................
sprite heart 8x8 pal=main
.kk.kk..
krrkrrk.
krrrrrk.
krrrrrk.
.krrrk..
..krk...
...k....
........
sprite heart0 8x8 pal=main
.kk.kk..
kmmkmmk.
kmmmmmk.
kmmmmmk.
.kmmmk..
..kmk...
...k....
........

-- ---------- tiles ----------
tile sand 16x16 pal=main
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aataaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaataaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaataaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaataa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
atlaaaaaataaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
tile water 16x16 pal=main flags=solid
uuuuuuuuuuuuuuuu
uuuuuuuuuuuuuuuu
uuuuuuuuuuuuuuuu
uuvvuuuuuuvvuuuu
uuuuuuuuuuuuuuuu
uuuuuuuuuuuuuuuu
uuuuuuuuuuuuuuuu
uuuuuvvuuuuuvvuu
uuuuuuuuuuuuuuuu
uuuuuuuuuuuuuuuu
uuvvuuuuuuvvuuuu
uuuuuuuuuuuuuuuu
uuuuuuuuuuuuuuuu
uuuuuvvuuuuuvvuu
uuuuuuuuuuuuuuuu
uuuuuuuuuuuuuuuu
tile rock 16x16 pal=main flags=solid
kkkkkkkkkkkkkkkk
kllllllllllllllk
kllllllllllllllk
kllllllllllllllk
kllllllllllllllk
klllllmmmllllllk
kllllllllllllllk
kllllllllllllllk
kllllllllllllllk
klllllllmmmllllk
kllllllllllllllk
kllllllllllllllk
kllllllllllllllk
kllllllllllllllk
kllllllllllllllk
kkkkkkkkkkkkkkkk
tile ship 16x16 pal=main flags=exit
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaakaraaaaaa
aaaaaaakrraaaaaa
aaaaaaakraaaaaaa
aaaaaaakaaaaaaaa
aaaaaaakaaaaaaaa
aaaaaaakaaaaaaaa
aaaaaakkkaaaaaaa
aaakooooooookaaa
aakooooooooookaa
aaakooooooookaaa
aaaaakooookaaaaa
aaaaaaakkaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa

-- ---------- the island: 20x15 tiles; row 0 sits under the HUD ----------
map island 20x15
legend # water  , sand  ^ rock  V ship
legend P @hero:sand  * @chest:sand  C @crab:sand  B @parrot:sand
####################
#,,,,,,,,,,,,,,,,,,#
#,,,,,,,,,,,,,,,*,,#
#,,,,,,,,,,,,,,,,,,#
#,,,,^^,,,,,,,,,,,,#
#,,,,,,,,,,,,,,,,,,#
#,P,B,,,,,,,,,,,,,,#
#,,,,,,,,,*,,,,,,,V#
#,,,,,,,,,,,,,,,,,,#
#,,,,,,,,,,,^^,,,,,#
#,,,,,,,,,,,,,,,,,,#
#,,,,,,,,,,,,,C,,,,#
#,,*,,,,,,,,,,,,C,,#
#,,,,,,,,,,,,,,,,,,#
####################

-- ---------- audio ----------
instrument squeeze from=organ vibrato=0.35,5.5

song shanty bpm=126
  lead  @squeeze o5 l4 [a g f e | f g a b | a g f e | d e f g | f a >c <a | g e c e | g a b >d | <c b a2]2
  harm  @epiano v9 o4 l2 [a c | g b | a c | e g | f a | c e | g b | a c]2
  bass  @bass o2 l2 [a a | g g | a a | e e | f f | c c | g g | a a]2
  drums @drums [k8 h8 s8 h8 k8 h8 s8 h8]16

sfx treasure notes="o5 l16 c e g >c e g >c4" inst=bell vol=0.85 bpm=160
